[package]
name = "slip10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-compact = "0.1"
hex = "0.4"
hmac = "0.11"
regex = "1"
sha2 = "0.9"